# Generated by Django 6.0.5 on 2026-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='seccion',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
    ]
