# Generated by Django 6.0.5 on 2026-06-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0002_maestro_fecha_nac'),
        ('Maestros', '0002_alumno_grado_alumno_seccion_alter_alumno_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='seccion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Directora.gradoseccion', verbose_name='Grado y Sección'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
