# Generated by Django 6.0.5 on 2026-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0003_alter_alumno_options_remove_alumno_grado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='grado_seccion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='seccion',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
