# Generated by Django 6.0.5 on 2026-06-08 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0002_maestro_fecha_nac'),
        ('Maestros', '0004_remove_alumno_grado_seccion_alumno_grado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='seccion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='Directora.gradoseccion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.CharField(default='Mañana', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('D', 'Demérito'), ('R', 'Redención'), ('RC', 'Reconocimiento')], max_length=2)),
                ('sub_letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('responsable_redencion', models.CharField(blank=True, max_length=150, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tarjeta', to='Maestros.alumno')),
                ('maestro_registra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demeritos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
