# Generated by Django 6.0.5 on 2026-06-08 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0005_alter_alumno_options_remove_alumno_grado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotarjeta',
            options={'ordering': ['fecha', 'id'], 'verbose_name': 'Registro de Tarjeta', 'verbose_name_plural': 'Registros de Tarjetas'},
        ),
        migrations.AddField(
            model_name='registrotarjeta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registrotarjeta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrotarjeta',
            name='maestro_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demeritos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
