# Generated by Django 6.0.5 on 2026-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0006_alter_registrotarjeta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotarjeta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='registrotarjeta',
            name='reconocimiento_letra',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registrotarjeta',
            name='redencion_letra',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registrotarjeta',
            name='tiene_reconocimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrotarjeta',
            name='tiene_redencion',
            field=models.BooleanField(default=False),
        ),
    ]
