# Generated by Django 6.0.5 on 2026-06-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0007_remove_registrotarjeta_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotarjeta',
            name='reconocimiento_letra',
        ),
        migrations.RemoveField(
            model_name='registrotarjeta',
            name='redencion_letra',
        ),
        migrations.RemoveField(
            model_name='registrotarjeta',
            name='tiene_reconocimiento',
        ),
        migrations.RemoveField(
            model_name='registrotarjeta',
            name='tiene_redencion',
        ),
    ]
