# Generated by Django 6.0.5 on 2026-06-10 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0008_remove_registrotarjeta_reconocimiento_letra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotarjeta',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
