# Generated by Django 6.0.5 on 2026-09-10 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0010_alter_maestro_fecha_actualizacion_and_more'),
        ('Maestros', '0009_alter_registrotarjeta_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('bloque', models.PositiveSmallIntegerField(help_text='Número de bloque de clase (1 a 7)')),
                ('anio_lectivo', models.PositiveIntegerField(default=2026)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_clase', to='Directora.maestro')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Directora.gradoseccion')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Directora.materia')),
            ],
            options={
                'verbose_name': 'Horario de Clase',
                'verbose_name_plural': 'Horarios de Clases',
                'unique_together': {('docente', 'dia', 'bloque', 'anio_lectivo'), ('grado_seccion', 'dia', 'bloque', 'anio_lectivo')},
            },
        ),
    ]
