# Generated by Django 6.0.5 on 2026-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0010_horarioclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioclase',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado para Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=15, verbose_name='Estado de Aprobación'),
        ),
        migrations.AddField(
            model_name='horarioclase',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Retroalimentación o motivo de rechazo de Dirección', null=True),
        ),
    ]
