# Generated by Django 6.0.5 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0011_horarioclase_estado_horarioclase_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioclase',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='estado',
            field=models.CharField(
                choices=[
                    ('BORRADOR', 'Borrador'),
                    ('ENVIADO', 'Enviado para Aprobación'),
                    ('APROBADO', 'Aprobado'),
                    ('RECHAZADO', 'Rechazado'),
                    ('PUBLICADO', 'Publicado'),
                ],
                default='BORRADOR',
                max_length=15,
                verbose_name='Estado de Aprobación',
            ),
        ),
    ]
