# Generated by Django 6.0.5 on 2026-05-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
