# Generated by Django 6.0.5 on 2026-05-29 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Grado y Sección',
                'verbose_name_plural': 'Grados y Secciones',
                'unique_together': {('grado', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('grado_a_cargo', models.ForeignKey(blank=True, help_text='Grado y sección que el maestro tiene asignado como orientador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maestro_encargado', to='Directora.gradoseccion')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maestro_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
            },
        ),
    ]
