# Generated by Django 6.0.5 on 2026-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='fecha_nac',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
