# Generated by Django 6.0.5 on 2026-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0002_maestro_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradoseccion',
            name='grado',
            field=models.CharField(choices=[('Parvularia', [('PK4', 'Parvularia 4 años'), ('PK5', 'Parvularia 5 años')]), ('Básica Ciclo I', [('1G', '1° Grado'), ('2G', '2° Grado'), ('3G', '3° Grado')]), ('Básica Ciclo II', [('4G', '4° Grado'), ('5G', '5° Grado'), ('6G', '6° Grado')]), ('Básica Ciclo III', [('7G', '7° Grado'), ('8G', '8° Grado'), ('9G', '9° Grado')]), ('Bachillerato', [('1B', '1° Año de Bachillerato'), ('2B', '2° Año de Bachillerato'), ('3B', '3° Año de Bachillerato (Técnico)')])], help_text='Seleccione el nivel académico oficial', max_length=20),
        ),
    ]
