# Generated by Django 6.0.5 on 2026-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0003_alter_gradoseccion_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradoseccion',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad máxima de estudiantes permitidos'),
        ),
        migrations.AlterField(
            model_name='gradoseccion',
            name='grado',
            field=models.CharField(choices=[('Parvularia', [('PK4', 'Parvularia 4 años'), ('PK5', 'Parvularia 5 años')]), ('Básica Ciclo I', [('1G', '1° Grado'), ('2G', '2° Grado'), ('3G', '3° Grado')]), ('Básica Ciclo II', [('4G', '4° Grado'), ('5G', '5° Grado'), ('6G', '6° Grado')]), ('Básica Ciclo III', [('7G', '7° Grado'), ('8G', '8° Grado'), ('9G', '9° Grado')])], help_text='Seleccione el nivel académico oficial', max_length=20),
        ),
    ]
