# Generated by Django 6.0.5 on 2026-06-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0004_gradoseccion_cupo_maximo_alter_gradoseccion_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='grado_a_cargo',
        ),
        migrations.AddField(
            model_name='gradoseccion',
            name='maestro_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados_a_cargo', to='Directora.maestro'),
        ),
    ]
