# Generated by Django 6.0.5 on 2026-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0005_remove_maestro_grado_a_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradoseccion',
            name='grado',
            field=models.CharField(choices=[('Parvularia', [('PK', 'Parvularia')]), ('Básica Ciclo I', [('1G', '1° Grado'), ('2G', '2° Grado'), ('3G', '3° Grado')]), ('Básica Ciclo II', [('4G', '4° Grado'), ('5G', '5° Grado'), ('6G', '6° Grado')]), ('Básica Ciclo III', [('7G', '7° Grado'), ('8G', '8° Grado'), ('9G', '9° Grado')])], help_text='Seleccione el nivel académico oficial', max_length=20),
        ),
    ]
