# Generated by Django 6.0.5 on 2026-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0006_alter_gradoseccion_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradoseccion',
            name='turno',
            field=models.CharField(default='mañana', max_length=50),
        ),
    ]
