# Generated by Django 6.0.5 on 2026-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0007_gradoseccion_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradoseccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
