# Generated by Django 6.0.5 on 2026-09-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0009_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='color',
            field=models.CharField(default='#D6E4FF', max_length=7),
        ),
        migrations.CreateModel(
            name='AsignacionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.PositiveIntegerField(default=2026, verbose_name='Año Lectivo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_impartidas', to='Directora.maestro', verbose_name='Docente Asignado')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_distribuidas', to='Directora.gradoseccion', verbose_name='Grado y Sección')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Directora.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Asignación de Materia',
                'verbose_name_plural': 'Asignaciones de Materias',
                'unique_together': {('grado_seccion', 'materia', 'anio_lectivo')},
            },
        ),
    ]
