# Generated by Django 6.0.5 on 2026-09-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0010_alter_maestro_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionBloqueMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('bloque', models.PositiveSmallIntegerField(choices=[(1, '07:00 - 07:45'), (2, '07:45 - 08:30'), (3, '09:00 - 09:45'), (4, '09:45 - 10:30'), (5, '10:30 - 11:15')])),
                ('anio_lectivo', models.PositiveIntegerField(default=2026, verbose_name='Año Lectivo')),
                ('activo', models.BooleanField(default=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_asignados', to='Directora.maestro', verbose_name='Maestro')),
            ],
            options={
                'verbose_name': 'Asignación de bloque a maestro',
                'verbose_name_plural': 'Asignaciones de bloques a maestros',
                'ordering': ['maestro', 'dia', 'bloque'],
                'constraints': [models.UniqueConstraint(fields=('maestro', 'dia', 'bloque', 'anio_lectivo'), name='bloque_unico_por_maestro_y_anio')],
            },
        ),
    ]
