# Generated by Django 6.0.5 on 2026-09-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0012_asignacionbloquemaestro_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='bloques_semanales',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
