# Generated by Django 6.0.5 on 2026-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directora', '0013_materia_bloques_semanales'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='nivel_aplicable',
            field=models.CharField(choices=[('PARVULARIA', 'Solo Parvularia'), ('BASICA', 'Solo Básica (1° a 6°)'), ('TERCER', 'Solo Tercer Ciclo (7° a 9°)'), ('BASICA_Y_TERCER', 'Básica y Tercer Ciclo')], default='BASICA_Y_TERCER', max_length=20),
        ),
    ]
